import { INodeProperties } from 'n8n-workflow';

export const productOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['product'],
      },
    },
    options: [
      {
        name: 'Create',
        value: 'create',
        description: 'Create a product',
        action: 'Create a product',
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Get a product',
        action: 'Get a product',
      },
      {
        name: 'Get Many',
        value: 'getAll',
        description: 'Get many products',
        action: 'Get many products',
      },
      {
        name: 'Update',
        value: 'update',
        description: 'Update a product',
        action: 'Update a product',
      },
    ],
    default: 'get',
  },
];

export const productFields: INodeProperties[] = [
  // GET / UPDATE — Product GUID or Code
  {
    displayName: 'Product Code or GUID',
    name: 'productCode',
    type: 'string',
    required: true,
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['get', 'update'],
      },
    },
    default: '',
    description: 'The product code or GUID of the product',
  },

  // GET ALL operations
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['getAll'],
      },
    },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['getAll'],
        returnAll: [false],
      },
    },
    typeOptions: {
      minValue: 1,
      maxValue: 200,
    },
    default: 50,
    description: 'Max number of results to return',
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['getAll'],
      },
    },
    options: [
      {
        displayName: 'Barcode',
        name: 'barcode',
        type: 'string',
        default: '',
        description: 'Filter by barcode',
      },
      {
        displayName: 'Brand',
        name: 'brand',
        type: 'string',
        default: '',
        description: 'Filter by brand',
      },
      {
        displayName: 'Include Obsolete',
        name: 'includeObsolete',
        type: 'boolean',
        default: false,
        description: 'Whether to include obsolete products',
      },
      {
        displayName: 'Exclude Assembled',
        name: 'excludeAssembled',
        type: 'boolean',
        default: false,
        description: 'Whether to exclude assembled products from results',
      },
      {
        displayName: 'Exclude Components',
        name: 'excludeComponents',
        type: 'boolean',
        default: false,
        description: 'Whether to exclude component products from results',
      },
      {
        displayName: 'Modified Since',
        name: 'modifiedSince',
        type: 'dateTime',
        default: '',
        description: 'Filter products modified since this date/time',
      },
      {
        displayName: 'Order By',
        name: 'orderBy',
        type: 'string',
        default: '',
        description: 'Field to order results by',
      },
      {
        displayName: 'Product Group',
        name: 'productGroup',
        type: 'string',
        default: '',
        description: 'Filter by product group name',
      },
      {
        displayName: 'Search Term',
        name: 'search',
        type: 'string',
        default: '',
        description: 'Search term to filter products (searches in code, description, etc.)',
      },
      {
        displayName: 'Sell Price Tier',
        name: 'sellPriceTier',
        type: 'string',
        default: '',
        description: 'Filter by sell price tier',
      },
      {
        displayName: 'Sort',
        name: 'sort',
        type: 'options',
        options: [
          { name: 'Ascending', value: 'asc' },
          { name: 'Descending', value: 'desc' },
        ],
        default: 'asc',
        description: 'Sort direction for results',
      },
      {
        displayName: 'Supplier',
        name: 'supplier',
        type: 'string',
        default: '',
        description: 'Filter by supplier name',
      },
      {
        displayName: 'Supplier Code',
        name: 'supplierCode',
        type: 'string',
        default: '',
        description: 'Filter by supplier code',
      },
    ],
  },

  // CREATE — required fields
  {
    displayName: 'Product Code',
    name: 'productCodeCreate',
    type: 'string',
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['create'],
      },
    },
    default: '',
    required: true,
    description: 'The unique product code',
  },
  {
    displayName: 'Product Description',
    name: 'productDescription',
    type: 'string',
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['create'],
      },
    },
    default: '',
    required: true,
    description: 'The product description',
  },

  // CREATE/UPDATE — Product Details collection
  {
    displayName: 'Product Details',
    name: 'productDetails',
    type: 'collection',
    placeholder: 'Add Product Detail',
    displayOptions: {
      show: {
        resource: ['product'],
        operation: ['create', 'update'],
      },
    },
    default: {},
    options: [
      {
        displayName: 'Average Cost',
        name: 'averageCost',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The average cost of the product',
      },
      {
        displayName: 'Barcode',
        name: 'barcode',
        type: 'string',
        default: '',
        description: 'The product barcode',
      },
      {
        displayName: 'Bin Location',
        name: 'binLocation',
        type: 'string',
        default: '',
        description: 'The bin location in the warehouse',
      },
      {
        displayName: 'Brand',
        name: 'brand',
        type: 'string',
        default: '',
        description: 'The product brand',
      },
      {
        displayName: 'Default Purchase Price',
        name: 'defaultPurchasePrice',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The default purchase price',
      },
      {
        displayName: 'Default Sell Price',
        name: 'defaultSellPrice',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The default sell price',
      },
      {
        displayName: 'Depth',
        name: 'depth',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The product depth',
      },
      {
        displayName: 'Height',
        name: 'height',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The product height',
      },
      {
        displayName: 'Is Assembled',
        name: 'isAssembled',
        type: 'boolean',
        default: false,
        description: 'Whether this is an assembled product',
      },
      {
        displayName: 'Is Component',
        name: 'isComponent',
        type: 'boolean',
        default: false,
        description: 'Whether this product is a component',
      },
      {
        displayName: 'Is Sellable',
        name: 'isSellable',
        type: 'boolean',
        default: true,
        description: 'Whether this product can be sold',
      },
      {
        displayName: 'Last Cost',
        name: 'lastCost',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The last cost of the product',
      },
      {
        displayName: 'Maximum Stock Alert Level',
        name: 'maxStockAlertLevel',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The maximum stock alert level',
      },
      {
        displayName: 'Minimum Order Quantity',
        name: 'minimumOrderQuantity',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The minimum order quantity',
      },
      {
        displayName: 'Minimum Sell Price',
        name: 'minimumSellPrice',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The minimum sell price',
      },
      {
        displayName: 'Minimum Stock Alert Level',
        name: 'minStockAlertLevel',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The minimum stock alert level',
      },
      {
        displayName: 'Never Diminishing',
        name: 'neverDiminishing',
        type: 'boolean',
        default: false,
        description: 'Whether the product stock never diminishes',
      },
      {
        displayName: 'Notes',
        name: 'notes',
        type: 'string',
        typeOptions: { rows: 4 },
        default: '',
        description: 'Notes about the product',
      },
      {
        displayName: 'Obsolete',
        name: 'obsolete',
        type: 'boolean',
        default: false,
        description: 'Whether the product is obsolete',
      },
      {
        displayName: 'Pack Size',
        name: 'packSize',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The pack size',
      },
      {
        displayName: 'Product Description',
        name: 'productDescription',
        type: 'string',
        default: '',
        description: 'The product description (for update)',
        displayOptions: {
          show: {
            '/operation': ['update'],
          },
        },
      },
      {
        displayName: 'Product Group',
        name: 'productGroup',
        type: 'string',
        default: '',
        description: 'The product group name',
      },
      {
        displayName: 'Re-Order Level',
        name: 'reOrderLevel',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The re-order level',
      },
      {
        displayName: 'Sell Price Tier 1',
        name: 'sellPriceTier1',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 1',
      },
      {
        displayName: 'Sell Price Tier 2',
        name: 'sellPriceTier2',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 2',
      },
      {
        displayName: 'Sell Price Tier 3',
        name: 'sellPriceTier3',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 3',
      },
      {
        displayName: 'Sell Price Tier 4',
        name: 'sellPriceTier4',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 4',
      },
      {
        displayName: 'Sell Price Tier 5',
        name: 'sellPriceTier5',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 5',
      },
      {
        displayName: 'Sell Price Tier 6',
        name: 'sellPriceTier6',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 6',
      },
      {
        displayName: 'Sell Price Tier 7',
        name: 'sellPriceTier7',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 7',
      },
      {
        displayName: 'Sell Price Tier 8',
        name: 'sellPriceTier8',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 8',
      },
      {
        displayName: 'Sell Price Tier 9',
        name: 'sellPriceTier9',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 9',
      },
      {
        displayName: 'Sell Price Tier 10',
        name: 'sellPriceTier10',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'Sell price tier 10',
      },
      {
        displayName: 'Supplier Code',
        name: 'supplierCode',
        type: 'string',
        default: '',
        description: 'The default supplier code',
      },
      {
        displayName: 'Supplier Product Code',
        name: 'supplierProductCode',
        type: 'string',
        default: '',
        description: "The supplier's product code",
      },
      {
        displayName: 'Tax Code',
        name: 'taxablePurchase',
        type: 'string',
        default: '',
        description: 'The purchase tax code',
      },
      {
        displayName: 'Tax Code (Sales)',
        name: 'taxableSales',
        type: 'string',
        default: '',
        description: 'The sales tax code',
      },
      {
        displayName: 'Unit of Measure',
        name: 'unitOfMeasure',
        type: 'string',
        default: '',
        description: 'The unit of measure (e.g. Each, Kg, Litre)',
      },
      {
        displayName: 'Weight',
        name: 'weight',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The product weight',
      },
      {
        displayName: 'Width',
        name: 'width',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The product width',
      },
      {
        displayName: 'Xero Cost of Goods Account',
        name: 'xeroCostOfGoodsAccount',
        type: 'string',
        default: '',
        description: 'The Xero cost of goods account code',
      },
      {
        displayName: 'Xero Sales Account',
        name: 'xeroSalesAccount',
        type: 'string',
        default: '',
        description: 'The Xero sales account code',
      },
    ],
  },
];
