import { INodeProperties } from 'n8n-workflow';

export const salesOrderOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['salesOrder'],
      },
    },
    options: [
      {
        name: 'Complete',
        value: 'complete',
        description: 'Complete a sales order',
        action: 'Complete a sales order',
      },
      {
        name: 'Create',
        value: 'create',
        description: 'Create a sales order',
        action: 'Create a sales order',
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Get a sales order',
        action: 'Get a sales order',
      },
      {
        name: 'Get Many',
        value: 'getAll',
        description: 'Get many sales orders',
        action: 'Get many sales orders',
      },
      {
        name: 'Update',
        value: 'update',
        description: 'Update a sales order',
        action: 'Update a sales order',
      },
    ],
    default: 'get',
  },
];

export const salesOrderFields: INodeProperties[] = [
  // GET / UPDATE / COMPLETE — Sales Order GUID
  {
    displayName: 'Sales Order GUID',
    name: 'salesOrderGuid',
    type: 'string',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['get', 'update', 'complete'],
      },
    },
    default: '',
    required: true,
    description: 'The GUID of the sales order',
  },

  // GET ALL operations
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getAll'],
      },
    },
    default: false,
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getAll'],
        returnAll: [false],
      },
    },
    typeOptions: {
      minValue: 1,
    },
    default: 50,
    description: 'Max number of results to return',
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getAll'],
      },
    },
    options: [
      {
        displayName: 'Batch Numbers',
        name: 'batchNumbers',
        type: 'string',
        default: '',
        description: 'Filter by batch numbers',
      },
      {
        displayName: 'Customer Code',
        name: 'customerCode',
        type: 'string',
        default: '',
        description: 'Filter by customer code',
      },
      {
        displayName: 'Customer Name',
        name: 'customerName',
        type: 'string',
        default: '',
        description: 'Filter by customer name',
      },
      {
        displayName: 'Delivery Method',
        name: 'deliveryMethod',
        type: 'string',
        default: '',
        description: 'Filter by delivery method',
      },
      {
        displayName: 'Delivery Name',
        name: 'deliveryName',
        type: 'string',
        default: '',
        description: 'Filter by delivery name',
      },
      {
        displayName: 'End Date',
        name: 'endDate',
        type: 'dateTime',
        default: '',
        description: 'End date for filtering sales orders',
      },
      {
        displayName: 'Modified Since',
        name: 'modifiedSince',
        type: 'dateTime',
        default: '',
        description: 'Filter orders modified since this date/time',
      },
      {
        displayName: 'Order By',
        name: 'orderBy',
        type: 'string',
        default: '',
        description: 'Field to order results by',
      },
      {
        displayName: 'Order Number',
        name: 'orderNumber',
        type: 'string',
        default: '',
        description: 'Filter by order number',
      },
      {
        displayName: 'Order Status',
        name: 'orderStatus',
        type: 'options',
        options: [
          { name: 'Parked', value: 'Parked' },
          { name: 'Placed', value: 'Placed' },
          { name: 'Backordered', value: 'Backordered' },
          { name: 'Completed', value: 'Completed' },
        ],
        default: 'Parked',
        description: 'Filter by order status',
      },
      {
        displayName: 'Sales Person',
        name: 'salesPerson',
        type: 'string',
        default: '',
        description: 'Filter by salesperson name',
      },
      {
        displayName: 'Serials',
        name: 'serials',
        type: 'string',
        default: '',
        description: 'Filter by serial numbers',
      },
      {
        displayName: 'Sort',
        name: 'sort',
        type: 'options',
        options: [
          { name: 'Ascending', value: 'asc' },
          { name: 'Descending', value: 'desc' },
        ],
        default: 'asc',
        description: 'Sort direction for results',
      },
      {
        displayName: 'Source ID',
        name: 'sourceId',
        type: 'string',
        default: '',
        description: 'Filter by external source ID',
      },
      {
        displayName: 'Start Date',
        name: 'startDate',
        type: 'dateTime',
        default: '',
        description: 'Start date for filtering sales orders',
      },
      {
        displayName: 'Warehouse Code',
        name: 'warehouseCode',
        type: 'string',
        default: '',
        description: 'Filter by warehouse code',
      },
      {
        displayName: 'Warehouse Name',
        name: 'warehouseName',
        type: 'string',
        default: '',
        description: 'Filter by warehouse name',
      },
    ],
  },

  // CREATE — required fields
  {
    displayName: 'Customer Code',
    name: 'customerCode',
    type: 'string',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['create'],
      },
    },
    default: '',
    required: true,
    description: 'The customer code for the sales order',
  },

  // CREATE/UPDATE — Sales Order Details collection
  {
    displayName: 'Sales Order Details',
    name: 'salesOrderDetails',
    type: 'collection',
    placeholder: 'Add Sales Order Detail',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['create', 'update'],
      },
    },
    default: {},
    options: [
      {
        displayName: 'Comments',
        name: 'comments',
        type: 'string',
        typeOptions: { rows: 4 },
        default: '',
        description: 'Comments for the sales order',
      },
      {
        displayName: 'Currency Code',
        name: 'currencyCode',
        type: 'string',
        default: '',
        description: 'The currency code (e.g. NZD, USD)',
      },
      {
        displayName: 'Customer Ref',
        name: 'customerRef',
        type: 'string',
        default: '',
        description: 'The customer reference / purchase order number',
      },
      {
        displayName: 'Delivery City',
        name: 'deliveryCity',
        type: 'string',
        default: '',
        description: 'Delivery address city',
      },
      {
        displayName: 'Delivery Country',
        name: 'deliveryCountry',
        type: 'string',
        default: '',
        description: 'Delivery address country',
      },
      {
        displayName: 'Delivery Instructions',
        name: 'deliveryInstruction',
        type: 'string',
        typeOptions: { rows: 3 },
        default: '',
        description: 'Special instructions for delivery',
      },
      {
        displayName: 'Delivery Method',
        name: 'deliveryMethod',
        type: 'string',
        default: '',
      },
      {
        displayName: 'Delivery Name',
        name: 'deliveryName',
        type: 'string',
        default: '',
        description: 'Delivery recipient name',
      },
      {
        displayName: 'Delivery Post Code',
        name: 'deliveryPostCode',
        type: 'string',
        default: '',
        description: 'Delivery address postal code',
      },
      {
        displayName: 'Delivery Region',
        name: 'deliveryRegion',
        type: 'string',
        default: '',
        description: 'Delivery address region/state',
      },
      {
        displayName: 'Delivery Street Address',
        name: 'deliveryStreetAddress',
        type: 'string',
        default: '',
        description: 'Delivery street address line 1',
      },
      {
        displayName: 'Delivery Street Address 2',
        name: 'deliveryStreetAddress2',
        type: 'string',
        default: '',
        description: 'Delivery street address line 2',
      },
      {
        displayName: 'Delivery Suburb',
        name: 'deliverySuburb',
        type: 'string',
        default: '',
        description: 'Delivery address suburb',
      },
      {
        displayName: 'Discount Rate',
        name: 'discountRate',
        type: 'number',
        typeOptions: { numberPrecision: 2, minValue: 0, maxValue: 100 },
        default: 0,
        description: 'The overall discount rate percentage',
      },
      {
        displayName: 'Exchange Rate',
        name: 'exchangeRate',
        type: 'number',
        typeOptions: { numberPrecision: 6 },
        default: 0,
        description: 'The exchange rate for the order currency',
      },
      {
        displayName: 'Order Date',
        name: 'orderDate',
        type: 'dateTime',
        default: '',
        description: 'The date of the sales order',
      },
      {
        displayName: 'Order Number',
        name: 'orderNumber',
        type: 'string',
        default: '',
      },
      {
        displayName: 'Payment Due Date',
        name: 'paymentDueDate',
        type: 'dateTime',
        default: '',
      },
      {
        displayName: 'Payment Term',
        name: 'paymentTerm',
        type: 'string',
        default: '',
        description: 'The payment term (e.g. 30 Days, COD)',
      },
      {
        displayName: 'Required Date',
        name: 'requiredDate',
        type: 'dateTime',
        default: '',
        description: 'The required/delivery date',
      },
      {
        displayName: 'Sales Order Group',
        name: 'salesOrderGroup',
        type: 'string',
        default: '',
      },
      {
        displayName: 'Salesperson Email',
        name: 'salespersonEmail',
        type: 'string',
        default: '',
        description: 'The email of the assigned salesperson',
      },
      {
        displayName: 'Salesperson Full Name',
        name: 'salespersonFullName',
        type: 'string',
        default: '',
        description: 'The full name of the assigned salesperson',
      },
      {
        displayName: 'Source ID',
        name: 'sourceId',
        type: 'string',
        default: '',
        description: 'External source identifier',
      },
      {
        displayName: 'Tax Code',
        name: 'taxCode',
        type: 'string',
        default: '',
        description: 'The tax code for the order',
      },
      {
        displayName: 'Tax Rate',
        name: 'taxRate',
        type: 'number',
        typeOptions: { numberPrecision: 4 },
        default: 0,
        description: 'The tax rate for the sales order',
      },
      {
        displayName: 'Warehouse Code',
        name: 'warehouseCode',
        type: 'string',
        default: '',
        description: 'The warehouse code to fulfill from',
      },
    ],
  },

  // CREATE/UPDATE — Line Items
  {
    displayName: 'Sales Order Line Items',
    name: 'salesOrderLineItems',
    type: 'fixedCollection',
    typeOptions: {
      multipleValues: true,
    },
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['create', 'update'],
      },
    },
    default: {},
    placeholder: 'Add Line Item',
    options: [
      {
        name: 'lineItems',
        displayName: 'Line Item',
        values: [
							{
								displayName: 'Comments',
								name: 'comments',
								type: 'string',
								default: '',
								description: 'Comments for this line item',
							},
							{
								displayName: 'Discount Rate',
								name: 'discountRate',
								type: 'number',
								default: 0,
								description: 'The discount rate percentage for this line',
							},
							{
								displayName: 'Due Date',
								name: 'dueDate',
								type: 'dateTime',
								default: '',
								description: 'The due date for this line item',
							},
							{
								displayName: 'Line Number',
								name: 'lineNumber',
								type: 'number',
								default: 0,
								description: 'The line number (for ordering)',
							},
							{
								displayName: 'Product Code',
								name: 'productCode',
								type: 'string',
								default: '',
									required:	true,
							},
							{
								displayName: 'Quantity',
								name: 'quantity',
								type: 'number',
								default: 1,
									required:	true,
								description: 'The order quantity',
							},
							{
								displayName: 'Tax Code',
								name: 'taxCode',
								type: 'string',
								default: '',
								description: 'The tax code for this line item',
							},
							{
								displayName: 'Unit Price',
								name: 'unitPrice',
								type: 'number',
								default: 0,
							},
						],
      },
    ],
  },
];
